### ISSUE TITLE
AttributeError data_split

### ISSUE THREAD

**Issue by z0v0z** [tarashakhurana/emergent-occ-forecasting#2]
When i use the python precast.py;  the error:  AttributeError:'nuScenesDataset' object has no attribute 'data_split'dkp.   my nuscense-devkit is 1.1.8

**Comment by tarashakhurana** [comment]
Can you create a PR with lines 137 and 138 deleted from precast.py? Sorry, those lines are a piece of remnant code from the cleanup.

**Comment by z0v0z** [comment]
ok，thanks
