### ISSUE TITLE
How do you deal with the final model evaluation

### ISSUE THREAD

**Issue by nunuisacat** [tarashakhurana/emergent-occ-forecasting#5]
Hello there, 
Thanks for your nice code.
I just found out that nuscenes didn't open source their test datasets' annotation.( for cheating avoiding)
And I checked the evaAI platform but didn't find evaluation possibility for planning.

How do you deal with this issue?
What do you use to finally evaluate your model?

Best regards,
RL

**Comment by tarashakhurana** [comment]
Hi, thanks for your question! All numbers in the main paper are on the nuScenes validation set (as noted in the table captions) for which annotations are available.
